### PR TITLE
Build & Test on 3 platforms with Github Actions

### PR DESCRIPTION
**Pull request by timfish**
This PR migrates from Travis to Github Actions testing on Ubuntu, macOS and Windows. If you'd rather keep Travis for Linux testing let me know and I can revert removing `travis.yml`.

This also fixes a test where `f64`'s were not being passed as arguments

### CODE REVIEW

**Comment by timfish** [comment]
Github actions obviously won't run in this repository unless it gets merged. You can however see the results on a PR in my fork [here](https://github.com/timfish/libffi-rs/commit/7a30d3fcbf442cf63fa6eb695e4bc8032fd0f95e/checks?check_suite_id=383687230).

**Comment by timfish** [comment]
I did some dirty `println!` testing in the `extern "C" fn add` and confirmed that incorrect numbers were getting passed as arguments. I've made a change to ensure that the arguments passed in the test are in fact `f64` like this:
```rust
let n = unsafe { cif.call(CodePtr(add as *mut _), &[arg(&5f64), arg(&&6f64)]) };
```
I have no idea why this would have no issues on macOS/Linux but fail on Windows 🤷‍♂️.

I have confirmed that the correct arguments are making it to the called function but now the test fails with:
```
---- src\middle\mod.rs - middle::Cif (line 71) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `11`,
 right: `0`', src\middle\mod.rs:14:1
```
I'll continue to look into this!

**Comment by timfish** [comment]
Actually, after the change ensuring the arguments are `f64`, this test now [fails on every platform](https://github.com/timfish/libffi-rs/runs/374800102) with the same result.

**Comment by timfish** [comment]
Test are now [all passing](https://github.com/timfish/libffi-rs/runs/375937513).

**Comment by YorickPeterse** [comment]
@timfish could you rebase for the 1.0.0 release? Then we can see if these changes are still OK, and merge them if they are :smiley:

**Comment by timfish** [comment]
Closing in favour of #13

**Pull request closed without merging**
